seoulhotver2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'subway/', include('subway.urls')),
    url(r'^$', include('subway.urls')),
]

subway/urls.py
from django.conf.urls import url, include
from .views import SubwayLV, subway_lazy, subway_now,main,bsbusy,bsempty,bsmy,bsvs,bscm,bsfd,bsch,bssh

app_name='subway'
urlpatterns = [
    url(r'^$', main, name='index'),
    url(r'busy/$', SubwayLV, name='busy'),
    url(r'lazy/$', subway_lazy, name='lazy'),
    url(r'now/$', subway_now, name='now'),

    url(r'1bz/$', bsbusy, name='1bz'),
    url(r'2em/$', bsempty, name='2em'),
    url(r'3my/$', bsmy, name='3my'),
    url(r'4vs/$', bsvs, name='4vs'),
    url(r'5cm/$', bscm, name='5vs'),
    url(r'6fd/$', bsfd, name='6fd'),
    url(r'chat/$', bsch, name='chat'),
    url(r'search/$', bssh, name='search'),
]

subway/models.py
from django.db import models

# Create your models here.

ON_OFF = (
    ('on', '승차'),
    ('off', '하차'),
    )

class dbModel(models.Model):
    record = models.CharField(max_length=100,)

    def __str__(self):
        return self.record
class SubwayModelQuerset(models.query.QuerySet):
    pass

class SubwayModelManager(models.Manager):
        pass

class SubwayModel(models.Model):
    ''' Seoul Hot place Subway model'''

    date = models.DateField(
                default='2017-01-01',
                verbose_name='date'
                )

    station = models.CharField(
                max_length=100,
                verbose_name='station',
                )

    line_number = models.CharField(
                max_length=10,
                default='1호선',
                verbose_name='subway line'
                )

    population0 = models.IntegerField(
                default=0,
                verbose_name='0',
                )

    population1 = models.IntegerField(
                default=0,
                verbose_name='1',
                )

    population2 = models.IntegerField(
                default=0,
                verbose_name='2',
                )

    population3 = models.IntegerField(
                default=0,
                verbose_name='3',
                )

    population4 = models.IntegerField(
                default=0,
                verbose_name='4',
                )

    population5 = models.IntegerField(
                default=0,
                verbose_name='5',
                )

    population6 = models.IntegerField(
                default=0,
                verbose_name='6',
                )

    population7 = models.IntegerField(
                default=0,
                verbose_name='7',
                )

    population8 = models.IntegerField(
                default=0,
                verbose_name='8',
                )

    population9 = models.IntegerField(
                default=0,
                verbose_name='9',
                )

    population10 = models.IntegerField(
                default=0,
                verbose_name='10',
                )

    population11 = models.IntegerField(
                default=0,
                verbose_name='11',
                )

    population12 = models.IntegerField(
                default=0,
                verbose_name='12',
                )

    population13 = models.IntegerField(
                default=0,
                verbose_name='13',
                )

    population14 = models.IntegerField(
                default=0,
                verbose_name='14',
                )

    population15 = models.IntegerField(
                default=0,
                verbose_name='15',
                )

    population16 = models.IntegerField(
                default=0,
                verbose_name='16',
                )

    population17 = models.IntegerField(
                default=0,
                verbose_name='17',
                )

    population18 = models.IntegerField(
                default=0,
                verbose_name='18',
                )

    population19 = models.IntegerField(
                default=0,
                verbose_name='19',
                )

    population20 = models.IntegerField(
                default=0,
                verbose_name='20',
                )

    population21 = models.IntegerField(
                default=0,
                verbose_name='21',
                )

    population22 = models.IntegerField(
                default=0,
                verbose_name='22',
                )

    population23 = models.IntegerField(
                default=0,
                verbose_name='23',
                )

    in_out = models.CharField(
                max_length=10,
                choices=ON_OFF,
                default='on',
                verbose_name='on and off',
                )

    def __str__(self):
        return self.station

subway/views.py
from django.shortcuts import render
from django.views.generic import ListView
import sys
from django.db.models import Q
# from django.utils import timezone

#from datetime import datetime
import datetime
from .models import SubwayModel,dbModel

import codecs
import operator
# Create your views here.
from urllib.request import urlopen
qs=dbModel.objects.all()
f=[]
for a in qs:
    f.append(str(a))


def SubwayLV(request):
    now = datetime.datetime.now()

    dayString = ['월', '화', '수', '목', '금', '토', '일']

    template_name  = 'subway/busy.html'

    qs = SubwayModel.objects.filter(date="2014-"+str(now.month)+'-'+str(now.day))

    biggest = 0

    if now.hour and (now.hour == 0):
        for query in qs:
            if query.population0 >  biggest:
                biggest = query.population0
        qs = qs.get(population0=biggest)

    elif now.hour and (now.hour == 1):
        for query in qs:
            if query.population1 >  biggest:
                biggest = query.population1
        qs = qs.get(population1=biggest)

    elif now.hour and (now.hour == 2):
        for query in qs:
            if query.population2 >  biggest:
                biggest = query.population2
        qs = qs.get(population2=biggest)

    elif now.hour and (now.hour == 3):
        for query in qs:
            if query.population3 >  biggest:
                biggest = query.population0
        qs = qs.get(population3=biggest)

    elif now.hour and (now.hour == 4):
        for query in qs:
            if query.population4 >  biggest:
                biggest = query.population4
        qs = qs.get(population4=biggest)

    elif now.hour and (now.hour == 5):
        for query in qs:
            if query.population5 >  biggest:
                biggest = query.population5
        qs = qs.get(population5=biggest)

    elif now.hour and (now.hour == 6):
        for query in qs:
            if query.population6 >  biggest:
                biggest = query.population6
        qs = qs.get(population6=biggest)

    elif now.hour and (now.hour == 7):
        for query in qs:
            if query.population7 >  biggest:
                biggest = query.population7
        qs = qs.get(population7=biggest)

    elif now.hour and (now.hour == 8):
        for query in qs:
            if query.population8 >  biggest:
                biggest = query.population8
        qs = qs.get(population8=biggest)

    elif now.hour and (now.hour == 9):
        for query in qs:
            if query.population9 >  biggest:
                biggest = query.population9
        qs = qs.get(population9=biggest)

    elif now.hour and (now.hour == 10):
        for query in qs:
            if query.population10 >  biggest:
                biggest = query.population10
        qs = qs.get(population10=biggest)

    elif now.hour and (now.hour == 11):
        for query in qs:
            if query.population11 >  biggest:
                biggest = query.population11
        qs = qs.get(population11=biggest)


    elif now.hour and (now.hour == 12):
        for query in qs:
            if query.population12 >  biggest:
                biggest = query.population12
        qs = qs.get(population12=biggest)

    elif now.hour and (now.hour == 13):
        for query in qs:
            if query.population13 >  biggest:
                biggest = query.population13
        qs = qs.get(population13=biggest)

    elif now.hour and (now.hour == 14):
        for query in qs:
            if query.population14 >  biggest:
                biggest = query.population14
        qs = qs.get(population14=biggest)

    elif now.hour and (now.hour == 15):
        for query in qs:
            if query.population15 >  biggest:
                biggest = query.population15
        qs = qs.get(population15=biggest)

    elif now.hour and (now.hour == 16):
        for query in qs:
            if query.population16 >  biggest:
                biggest = query.population16
        qs = qs.get(population16=biggest)

    elif now.hour and (now.hour == 17):
        for query in qs:
            if query.population17 >  biggest:
                biggest = query.population17
        qs = qs.get(population17=biggest)

    elif now.hour and (now.hour == 18):
        for query in qs:
            if query.population18 >  biggest:
                biggest = query.population18
        qs = qs.get(population18=biggest)

    elif now.hour and (now.hour == 19):
        for query in qs:
            if query.population19 >  biggest:
                biggest = query.population19
        qs = qs.get(population19=biggest)

    elif now.hour and (now.hour == 20):
        for query in qs:
            if query.population20 >  biggest:
                biggest = query.population20
        qs = qs.get(population20=biggest)

    elif now.hour and (now.hour == 21):
        for query in qs:
            if query.population21 >  biggest:
                biggest = query.population21
        qs = qs.get(population21=biggest)

    elif now.hour and (now.hour == 22):
        for query in qs:
            if query.population22 >  biggest:
                biggest = query.population22
        qs = qs.get(population22=biggest)

    elif now.hour and (now.hour == 23):
        for query in qs:
            if query.population23 >  biggest:
                biggest = query.population23
        qs = qs.get(population23=biggest)

    print(qs.station)

    context = {"station" : qs}

    return render(request, template_name, context)

def main(request):
    now = datetime.datetime.now()

    dayString = ['월', '화', '수', '목', '금', '토', '일']

    template_name  = 'subway/index.html'

    qs = SubwayModel.objects.filter(date="2014-"+str(now.month)+'-'+str(now.day))

    biggest = 0
    small_pk = 0
    values = 'query.population' + str(now.hour)
    for query in qs:
        if eval(values) > biggest:
            biggest = eval(values)
            small_pk = query.id
    if now.hour>1 or now.hour<5:
        qs.station='미집계 시간입니다'
    else:
        qs = qs.get(id=small_pk)


    context = {"station" : qs}

    return render(request, template_name, context)

def subway_lazy(request):
    now = datetime.datetime.now()

    dayString = ['월', '화', '수', '목', '금', '토', '일']

    template_name  = 'subway/busy.html'

    qs = SubwayModel.objects.filter(date="2014-"+str(now.month)+'-'+str(now.day))

    smallest = 100000
    values = 'query.population' + str(now.hour)
    for query in qs:
        if eval(values) < smallest:
            smallest = eval(values)
            small_pk = query.id
    qs = qs.get(id=small_pk)

    context = { "stations" : qs }

    template_name = 'subway/lazy.html'

    print (qs.station)

    return render(request, template_name, context)

def subway_now(request):
    now = datetime.datetime.now()

    template_name  = 'subway/busy.html'

    qs1 = SubwayModel.objects.get(date="2014-"+str(now.month)+'-'+str(now.day), station='도림천(247)', in_out='승차')
    qs2 = SubwayModel.objects.get(date="2014-"+str(now.month)+'-'+str(now.day), station='도림천(247)', in_out='하차')
    print(qs1)
    'qs.population' + str(now.hour)
    a = eval('qs1.population' + str(now.hour))
    b = eval('qs2.population' + str(now.hour))
    context = { 'station1': qs1, 'station2' : qs2 , 'pop':a+b}

    template_name='subway/now.html'

    return render(request, template_name, context)


def lanking(request):
    now = datetime.datetime.now()

    template_name  = 'subway/busy.html'

    qs = SubwayModel.objects.filter(date="2014-"+str(now.month)+'-'+str(now.day))

def bsbusy(request):
    tm=str(datetime.datetime.now()).split(':')[0]+'시 현재 서울 핫플 순위'
    daytmp = str(datetime.datetime.now()).split(' ')
    date = daytmp[0][5:10]
    time = int(daytmp[1][0:2])

    dayString = ['월', '화', '수', '목', '금', '토', '일']
    todaylist = []
    '''
    def weekday(year, month, day):
        year_1 = year / 100
        year_2 = year - year_1 * 100
        return dayString[(day + (month + 1) * 26 / 10 + year_2 + (year_2 / 4) + (year_1 / 4) - 2 * year_1 - 2) % 7]
    '''

    def weekday(year, month, day):
        return dayString[datetime.date(year, month, day).weekday()]

    odds = []
    for index, line in enumerate(f):
        lin = line[0:line.rfind(')') - 4] + line[line.rfind(')') + 1:]
        raw = lin.split('\t')
        rst = []
        if index % 2 == 0:
            for elemindex, elem in enumerate(raw):
                if elemindex == 0:
                    rst.append(str(elem))
                    ymd = str(elem).split('-')
                    rst.append(weekday(int(ymd[0]), int(ymd[1]), int(ymd[2])))
                elif elemindex == 1:
                    rst.append(elem)
                elif elemindex == 2:
                    rst.append(elem)
                elif elemindex != 3:
                    rst.append(int(elem))
        else:
            tmp = []
            for elemindex, elem in enumerate(raw):
                if elemindex > 3:
                    tmp.append(int(elem))
            odds.append(tmp)
        if len(rst) is not 0:
            todaylist.append(rst)

    for id, td in enumerate(odds):
        for i, t in enumerate(td):
            todaylist[id][4 + i] += t

    exact = []
    for qry in todaylist:
        if qry[0].endswith(date):
            exact.append(qry)

    sortrst = sorted(exact, key=operator.itemgetter(time + 4), reverse=True)
    context={'time':time+5,'now':tm,'blist':sortrst}
    template_name = 'subway/1bz.html'
    return render(request, template_name, context)

def bsempty(request):
    tm=str(datetime.datetime.now()).split(':')[0]+'시 현재 서울 콜플 순위'
    daytmp = str(datetime.datetime.now()).split(' ')
    date = daytmp[0][5:10]
    time = int(daytmp[1][0:2])

    dayString = ['월', '화', '수', '목', '금', '토', '일']
    todaylist = []
    '''
    def weekday(year, month, day):
        year_1 = year / 100
        year_2 = year - year_1 * 100

subway/templates/subway/2em.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load compute %}
        <!--bs 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>현재 혼잡 순위</title>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="../">So Hot! Seoul Hot Ple</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a class="page-scroll" href="../"></a>
                    </li>
              <li class="hidden">
                        <a class="page-scroll" href="../"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="../1bz">핫플 순위</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../2em">콜플 순위</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../3my">여긴 핫플?</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="../4vs">핫플 비교</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../5cm">통근/통학</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="../6fd">이달의 불금</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="../chat">핫플 채팅</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="../search">핫플 검색</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
       <br>
    <br>
    <br>
   <br>

    <div align="center">
    <div class="jumbotron">
        <br>
  <h2>{{ now }}</h2>
</div>
{% for sts in blist %}
    {% if forloop.counter < 11%}
{% ifequal forloop.counter 1 %}
     <div class="panel panel-primary">
                      {% else %}
  <div class="panel panel-info">
  {% endifequal %}
    <div class="panel-heading">{{ forloop.counter }}위</div>



<div class="panel-body">
    {% for st in sts %}
        {%  ifequal forloop.counter 3 %}
            {{ st }}
        {% endifequal %}
        {%  ifequal forloop.counter 4 %}
            <h4>{{ st }}</h4>
        {% endifequal %}
        {%  ifequal forloop.counter time %}
            <h3>{{ st }}명</h3> (현재 일 중 {{ st|percent:sts.28 }}%)
                        <div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow={{ st|percent:sts.28 }}   aria-valuemin="0" aria-valuemax="100" style="width: {{ st|percent:sts.28 }}%">
    <span class="sr-only">현재 일 중 {{ st|percent:sts.28 }} %</span>
  </div>
</div>
        {% endifequal %}
        {%  ifequal forloop.counter 29%}
            당일 누적 {{ st }}명
            <br>
        {% endifequal %}
    {% endfor %}
</div>
  </div>
        </div>
    {% endif %}
{% endfor %}
    </div>
</body>
</html>

subway/templates/subway/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="{% static "subway/css/main.css" %}" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		{% block head %}{% endblock %}

		<style>
		#forum{
		background-color: #2a2f4a;
		text-align: center;
		align-items: center;
		}
		</style>
  </head>


  <body>
    <div id="wrapper">

      <!-- Header -->
        <header id="header" class="alt">
          <a href="{% url "subway:index" %}" class="logo"><strong>Seoul Hot</strong> <span>by 잠못자는사람들</span></a>
          <nav>
            <a href="#menu">Menu</a>
          </nav>
        </header>

      <!-- Menu -->
        <nav id="menu">
          <ul class="links">
            <li><a href="{% url 'subway:1bz' %}">핫플 순위</a></li>
            <li><a href="{% url 'subway:2em' %}">콜플 순위</a></li>
            <li><a href="{% url 'subway:3my' %}">여긴 핫플?</a></li>
            <li><a href="{% url 'subway:4vs' %}">핫플 비교</a></li>
            <li><a href="{% url 'subway:5vs' %}">통근 / 통학</a></li>
            <li><a href="{% url 'subway:6fd' %}">이달의 불금</a></li>
            <li><a href="{% url 'subway:chat' %}">핫플 채팅</a></li>
            <li><a href="{% url 'subway:search' %}">핫플 검색</a></li>
            
          </ul>
        </nav>
    {% block body %}
    {% endblock %}
    <footer id="footer">
      <div class="inner">
        <ul class="icons">
          <li><a href="#" class="icon alt fa-twitter"><span class="label">Twitter</span></a></li>
          <li><a href="#" class="icon alt fa-facebook"><span class="label">Facebook</span></a></li>
          <li><a href="#" class="icon alt fa-instagram"><span class="label">Instagram</span></a></li>
          <li><a href="#" class="icon alt fa-github"><span class="label">GitHub</span></a></li>
          <li><a href="#" class="icon alt fa-linkedin"><span class="label">LinkedIn</span></a></li>
        </ul>
        <ul class="copyright">
          <li>&copy; Untitled</li>
          <li>Design: <a href="index.html">NOVELER</a></li>

        </ul>
      </div>
    </footer>

  </body>

  <script src="{% static "subway/js/jquery.min.js" %}"></script>
  <script src="{% static "subway/js/jquery.scrolly.min.js" %}"></script>
  <script src="{% static "subway/js/jquery.scrollex.min.js" %}"></script>
  <script src="{% static "subway/js/skel.min.js" %}"></script>
  <script src="{% static "subway/js/util.js" %}"></script>
  <!--[if lte IE 8]><script src="subway/js/ie/respond.min.js"></script><![endif]-->
  <script src="{% static "subway/js/main.js" %}"></script>

</html>

subway/templates/subway/busy.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    현재 가장 붐비는 지하철 역은 {{station.station}}역 입니다.
  </body>
</html>

subway/templates/subway/chat.html
{% extends 'subway/base.html' %}

{% block head %}
    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <!-- Firebase -->
    <script src="https://www.gstatic.com/firebasejs/3.3.0/firebase.js"></script>
    <!-- Firechat -->
    <link rel="stylesheet" href="https://cdn.firebase.com/libs/firechat/3.0.1/firechat.min.css" />
    <script src="https://cdn.firebase.com/libs/firechat/3.0.1/firechat.min.js"></script>
    <!-- Custom CSS -->
    <style>
      #firechat-wrapper {
        height: 475px;
        max-width: 325px;
        padding: 10px;
        border: 1px solid #ccc;
        background-color: #fff;
        margin: 50px auto;
        text-align: center;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        border-radius: 4px;
        -webkit-box-shadow: 0 5px 25px #666;
        -moz-box-shadow: 0 5px 25px #666;
        box-shadow: 0 5px 25px #666;
      }
    </style>
    
{% endblock %}
  <!--
    Example: Anonymous Authentication
    This example uses Firebase Simple Login to create "anonymous" user sessions in Firebase,
    meaning that user credentials are not required, though a user has a valid Firebase
    authentication token and security rules still apply.
    Requirements: in order to use this example with your own Firebase, you'll need to do the following:
      1. Apply the security rules at https://github.com/firebase/firechat/blob/master/rules.json
      2. Enable the "Anonymous" authentication provider in Forge
      3. Update the URL below to reference your Firebase
      4. Update the room id for auto-entry with a public room you have created
   -->
  {% block body %}
    <!--<? include "./left_menu.html";?>-->
    
    <div id="firechat-wrapper"></div>
    <script type="text/javascript">
      // Initialize Firebase SDK
      var config = {
        apiKey: "AIzaSyAm0i24WfjcdiGT_WtlaYqZZ7u4zKM2ffw",
        authDomain: "login-e8197.firebaseapp.com",
        databaseURL: "https://login-e8197.firebaseio.com"
      };
      firebase.initializeApp(config);
      // Get a reference to the Firebase Realtime Database
      var chatRef = firebase.database().ref("gangnam");
      // Create an instance of Firechat
      var chat = new FirechatUI(chatRef, document.getElementById("firechat-wrapper"));
      // Listen for authentication state changes
      firebase.auth().onAuthStateChanged(function(user) {
        if (user) {
          // If the user is logged in, set them as the Firechat user
          chat.setUser(user.uid, "Anonymous" + user.uid.substr(10, 8));
        } else {
          // If the user is not logged in, sign them in anonymously
          firebase.auth().signInAnonymously().catch(function(error) {
            console.log("Error signing user in anonymously:", error);
          });
        }
      });
    </script>
 {% endblock %}

subway/templates/subway/index.html
{% extends "subway/base.html" %}

		<!-- Wrapper -->

		{% block body %}

				<!-- Banner -->
					<section id="banner" class="major">
						<div class="inner">
							<header class="major">
								<h1>Seoul Hot</h1>
							</header>
							<div class="content">
								<p>Never <br />
								sleep</p>
								<ul class="actions">
									<li><a href="#two" class="button next scrolly">Get Started</a></li>
								</ul>
							</div>
						</div>
					</section>

							<section id="forum">
								<div class="inner">
									<header class="forum">
										<center><h3>Hot place now</h3></center>
									</header>


									<div class="box">
									<h1>
										 {{station.station}}
									</h1>
									</div>
								</div>
							</section>

				<!-- Main -->
					<div id="main">





						<!-- One -->
							<section id="two" class="tiles">
								<article>
									<span class="image">
										<img src="images/icon/history.jp" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url "subway:1bz" %}" class="link">핫 플레이스</a></h3>
										<p>이시각 지하철 복잡도 순위</p>
										<p>1위부터 10위까지</p>
									</header>
								</article>
								<article>
									<span class="image">
										<img src="images/icon/department.jp" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url 'subway:2em'%}" class="link">한산지역순</a></h3>
										<p>Department of Noveler</p>
									</header>
								</article>
								<article>
									<span class="image">
										<img src="images/icon/gallery.jp" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url 'subway:3my'%}" class="link">지금 내 지하철</a></h3>
										<p>Our photo is here</p>
									</header>
								</article>
								<article>
									<span class="image">
										<img src="images/icon/contact.jp" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url 'subway:4vs' %}" class="link">지역 vs 지역</a></h3>
										<p>Contact of Noveler</p>
									</header>
								</article>
								<article>
									<span class="image">
										<img src="images/pic06.jpg" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url 'subway:5vs'%}" class="link">통학 통근</a></h3>
										<p>미정</p>
									</header>
								</article>
								<article>
									<span class="image">
										<img src="images/pic06.jpg" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url 'subway:6fd'%}" class="link">이달의 불금</a></h3>
										<p>미정</p>
									</header>
								</article>
								<article>
									<span class="image">
										<img src="images/pic06.jpg" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url 'subway:chat'%}" class="link">핫플 채팅</a></h3>
										<p>미정</p>
									</header>
								</article>
								<article>
									<span class="image">
										<img src="images/pic06.jpg" alt="" />
									</span>
									<header class="major">
										<h3><a href="{% url 'subway:search'%}" class="link">통합검색</a></h3>
										<p>미정</p>
									</header>
								</article>
							</section>


					</div>

				<!-- Contact -->


				<!-- Footer -->

			</div>
		{% endblock %}
		<!-- Scripts -->

subway/templates/subway/lazy.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    가장 한산한 역은
      {{stations.station}}
    입니다.
  </body>
</html>